//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotaMatchMaster.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CampStackChecked {
            get {
                return ((bool)(this["CampStackChecked"]));
            }
            set {
                this["CampStackChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoomDevourCooldownChecked {
            get {
                return ((bool)(this["DoomDevourCooldownChecked"]));
            }
            set {
                this["DoomDevourCooldownChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HealingLotusSpawnChecked {
            get {
                return ((bool)(this["HealingLotusSpawnChecked"]));
            }
            set {
                this["HealingLotusSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MidasCooldownChecked {
            get {
                return ((bool)(this["MidasCooldownChecked"]));
            }
            set {
                this["MidasCooldownChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TokenAvailabilityChecked {
            get {
                return ((bool)(this["TokenAvailabilityChecked"]));
            }
            set {
                this["TokenAvailabilityChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TormentorSpawnChecked {
            get {
                return ((bool)(this["TormentorSpawnChecked"]));
            }
            set {
                this["TormentorSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WardPurchaseCooldownChecked {
            get {
                return ((bool)(this["WardPurchaseCooldownChecked"]));
            }
            set {
                this["WardPurchaseCooldownChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CampPullChecked {
            get {
                return ((bool)(this["CampPullChecked"]));
            }
            set {
                this["CampPullChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BountyRuneSpawnChecked {
            get {
                return ((bool)(this["BountyRuneSpawnChecked"]));
            }
            set {
                this["BountyRuneSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RuneSpawnChecked {
            get {
                return ((bool)(this["RuneSpawnChecked"]));
            }
            set {
                this["RuneSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WaterRuneSpawnChecked {
            get {
                return ((bool)(this["WaterRuneSpawnChecked"]));
            }
            set {
                this["WaterRuneSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WisdomRuneSpawnChecked {
            get {
                return ((bool)(this["WisdomRuneSpawnChecked"]));
            }
            set {
                this["WisdomRuneSpawnChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuybackCooldownChecked {
            get {
                return ((bool)(this["BuybackCooldownChecked"]));
            }
            set {
                this["BuybackCooldownChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrustyShovelCooldownChecked {
            get {
                return ((bool)(this["TrustyShovelCooldownChecked"]));
            }
            set {
                this["TrustyShovelCooldownChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PirateHatCooldownChecked {
            get {
                return ((bool)(this["PirateHatCooldownChecked"]));
            }
            set {
                this["PirateHatCooldownChecked"] = value;
            }
        }
    }
}
